In [18]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [19]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [20]:
one_hot('poor service',30)

[25, 17]

In [21]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[21, 11], [5, 12], [26, 5], [25, 6, 6], [2, 14, 20], [18, 11], [11, 14, 29], [25, 17], [25, 6], [11, 11]]


In [22]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[21 11  0  0]
 [ 5 12  0  0]
 [26  5  0  0]
 [25  6  6  0]
 [ 2 14 20  0]
 [18 11  0  0]
 [11 14 29  0]
 [25 17  0  0]
 [25  6  0  0]
 [11 11  0  0]]


In [24]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [25]:
X = padded_reviews
y = sentiment

In [26]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_7 (Flatten)         (None, 20)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
model.fit(X, y, epochs = 50, verbose=0)

In [30]:
loss, accuracy = model.evaluate(X, y)

1/1 [==============================] - 0s 14ms/step - loss: 0.6448 - accuracy: 1.0000


In [35]:
weights = model.get_layer("embedding").get_weights()[0]

In [36]:
len(weights)

30

In [38]:
weights[21]

array([ 0.00271839,  0.05909459, -0.04059333,  0.07548285,  0.06711853],
      dtype=float32)

In [39]:
weights[5]

array([ 0.07735401,  0.0607773 , -0.01755602,  0.03875973, -0.08156474],
      dtype=float32)